version: '3.8'
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - chroma
      - db
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - '8000:8000'
    # Use default settings
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nu_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
